### ISSUE TITLE
Na edição na lista de imagens, ao abrir novamente os novos itens não são adicionados a lista

### ISSUE THREAD

**Issue by fabiolamfleury** [lab-neuro-comp/Test-Platform#141]
- [ ] Verificar se ocorre o mesmo na lista de áudio

**Comment by gabrielalbino** [comment]
@fabiolamfleury o que pode tá causando esse erro é que o nome da lista vai incompleto quando clica em editar
Ex: Se eu clicar pra editar a lista "Avatar" ele mostra isso:
![image](https://user-images.githubusercontent.com/30835149/37654868-54d24830-2c22-11e8-9e21-659f8ace174a.png)
Aí quando eu adiciono as imagens e salvo a lista fica como Av_images

**Comment by fabiolamfleury** [comment]
@gabrielalbino acredito ter corrigido isso, você poderia conferir e fechar essa issue?
