### ISSUE TITLE
Criar ambiente que utilize o WPF

### ISSUE THREAD

**Issue by fabiolamfleury** [lab-neuro-comp/Test-Platform#143]
Assim, sugere-se para o nosso contexto, onde há necessidade de utilizar várias versões diferentes do windows, o WPF, e deve-se portanto configurar um ambiente para utilizá-lo, necessário o estudo das seguintes ferramentas para utilização:
https://mahapps.com/
https://www.syncfusion.com/

No syncfusion, caso não tenha instalado ele como admin do windows, deve-se seguir esse tutorial para instalar as bibliotecas necessárias:

https://help.syncfusion.com/common/essential-studio/utilities#assembly-manager

- [ ] Procurar ferramentas de teste de aceitação para WPF

**Comment by fabiolamfleury** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-overview
Arquitetura MVVM

**Comment by fabiolamfleury** [comment]
https://help.syncfusion.com/wpf/pattern-and-practices

**Comment by gabrielalbino** [comment]
@fabiolamfleury fechando essa issue pois não será mais utilizado wpf
