### ISSUE TITLE
Criar formulário para cadastro de participante

### ISSUE THREAD

**Issue by fabiolamfleury** [lab-neuro-comp/Test-Platform#180]
- [x] O Pesquisador deve conseguir cadastrar participantes

- [x] Ao executar o seu teste, o pesquisador deve conseguir escolher entre um participante cadastrado ou apenas digitar o nome dele (como já ocorre atualmente)

Baseado nesse formulário:
![image](https://user-images.githubusercontent.com/20935369/39158452-87be7726-4736-11e8-8323-b811a416b7b0.png)

**Comment by gabrielalbino** [comment]
@fabiolamfleury o que falta pra fechar essa issue?
