### ISSUE TITLE
ORGANIZAR ORDEM DOS ELEMENTOS NA COMBOBOX DE SELEÇÃO DE TIPO DE ESTIMULO NO STROOP TEST E TRADUZIR

### ISSUE THREAD

**Issue by gabrielalbino** [lab-neuro-comp/Test-Platform#187]
* a ordem dos elementos no tipo de estimulo no stroop test tá errada (ex: palavra e imagem muito abaixo do imagem e palavra)

**Comment by fabiolamfleury** [comment]
Você pode explicar um pouco mais sobre? Foi uma observação sua ou dito em reunião? A organização seria pela semântica dos tipos?

**Comment by gabrielalbino** [comment]
Tipo
Imagem e palavra proximo de palavra e imagem

Em Qui, 24 de mai de 2018 11:34, Fabíola Fleury <notifications@github.com>
escreveu:
