### ISSUE TITLE
Uma imagem se fixou no TR, ver imagem

### ISSUE THREAD

**Issue by anacog** [lab-neuro-comp/Test-Platform#218]
<img width="960" alt="teste" src="https://user-images.githubusercontent.com/20425803/44274949-e71b2c80-a219-11e8-9eee-d26239a505cb.png">

**Comment by fabiolamfleury** [comment]
Não estou conseguindo reproduzir esse erro, vou tentar no computador do laboratório

**Comment by fabiolamfleury** [comment]
Resolvido e conferido
