### ISSUE TITLE
Correção das labels na exportação/importação

### ISSUE THREAD

**Issue by fabiolamfleury** [lab-neuro-comp/Test-Platform#68]
- [x] Mudar mensagem de aviso sobre os arquivos: caso os arquivos já existam, ressaltar que não necessariamente tem o mesmo conteúdo

- [x] Na exportação/importação alterar o cabeçalho nome do arquivo para nome do programa/lista

**Comment by gabrielalbino** [comment]
@fabiolamfleury dei o push dessa na master por desatenção, mas resolvi.
